### PR TITLE
Document coroutine PDO limitation

### PR DESCRIPTION
**Pull request by codeliner**
Provide a narrative description of what you are trying to accomplish:

- [ ] Are you fixing a bug?
  - [ ] Detail how the bug is invoked currently.
  - [ ] Detail the original, incorrect behavior.
  - [ ] Detail the new, expected behavior.
  - [ ] Base your feature on the `master` branch, and submit against that branch.
  - [ ] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

- [ ] Are you creating a new feature?
  - [ ] Why is the new feature needed? What purpose does it serve?
  - [ ] How will users use the new feature?
  - [ ] Base your feature on the `develop` branch, and submit against that branch.
  - [ ] Add only one feature per pull request; split multiple features over multiple pull requests
  - [ ] Add tests for the new feature.
  - [ ] Add documentation for the new feature.
  - [ ] Add a `CHANGELOG.md` entry for the new feature.

- [ ] Is this related to quality assurance?
  

- [x] Is this related to documentation?
  As requested by @weierophinney on [twitter](https://twitter.com/mwop/status/1053644531206443008), this PR adds a hint to the docs regarding PDO limitation of Swoole coroutine feature. You can find a detailed bug report [here](https://github.com/swoole/swoole-src/issues/2051)

### CODE REVIEW

**Comment by huangzhhui** [comment]
I think the documentation should not tells everyone what drivers still block, should provide a white list that tells everyone what drivers that could change to coroutine driver.
And actually the Chinese Documentation tells that pdo_pgsql is still blocking.
https://wiki.swoole.com/wiki/page/965.html

**Comment by codeliner** [comment]
If I would only be able to read/understand Chinese ;) So this is not a bug but a known limitation.

Ok how do we want to handle it? I could add a google translate link to the docs. This way we don't need to maintain the list ourself: https://translate.google.com/translate?hl=de&sl=auto&tl=en&u=https%3A%2F%2Fwiki.swoole.com%2Fwiki%2Fpage%2F965.html

**Comment by huangzhhui** [comment]
You could use \Swoole\Coroutine\PostgreSQL client.
https://wiki.swoole.com/wiki/page/883.html
Or you could use TaskWorker to execute the blocking operations.

**Comment by xtreamwayz** [comment]
@codeliner According to the english docs it is supported (sort of) with Swoole\Coroutine\PostgreSQL: https://www.swoole.co.uk/docs/modules/swoole-coroutine

I'm guessing it's sort of a wrapper.

**Comment by codeliner** [comment]
yeah, I'm aware of \Swoole\Coroutine\PostgreSQL but that's not the point here. Docs say that PDO is supported, which is not exactly true. My hope was that I can use our [pdo-event-store](https://github.com/prooph/pdo-event-store) with Swoole without explicitly using an async connection.  

So I still think expressive docs should contain a hint. Otherwise you might think that you can enable Coroutine feature and every PDO query becomes non-blocking. This is really dangerous because you probably don't recognize the limitation until deployed to production.

**Comment by codeliner** [comment]
thx @huangzhhui I'll take a look at TaskWorkers

**Pull request merged**
