### PR TITLE
Added support of Swoole 4.1 coroutine

### PR DESCRIPTION
**Pull request by huangzhhui**
Swoole 4.1 is ready, there's a incredible feature that could let PDO, Mysqli, redis, soap, stream_socket_client, fsockopen,file_get_contents (Most of I/O driver) become a non-blocking async client needs just one line code `Swoole\Runtime::enableCorotuine()`.

> Notice that the documents in swoole official site about coroutine are outdated, I have been contacted with swoole developer team.

- [x] Are you creating a new feature?
  - [x] Why is the new feature needed? What purpose does it serve?
The server still running in I/O blocking driver before, even using swoole, when the  request handler processing in I/O request, like DB, Cache request, it will block the hold process, if the server running in 4 workers, and per request consumes 1 sec, the QPS is 4/sec, But, when running in coroutine, all I/O will switch to Non-Blocking driver, the QPS will be unlimited (Actually limited by memory of server, and limited by MySQL Server or Redis Server etc.).
  - [x] How will users use the new feature?
```
[
    'zend-expressive-swoole' => [
        'swoole-http-server' => [
            'options' => [
                'enable_coroutine' => true,
            ],
        ],
    ]
]
```
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [x] Add only one feature per pull request; split multiple features over multiple pull requests

I make some tests, the results are below, server running in coroutine mode about **1350 times** fater than non-coroutine mode in this test case.
> The tests result maybe wrong, because my MySQL server cannot handle the huge connection numbers like this, I have to develop a Connection Pool before this, anyone could provide another tests result would be better, but coroutine still faster than non-coroutine is a fact.
I write the code in a Controller as below.
```
$pdo = new \PDO($dsn, $user, $password);
$pdo->query('select sleep(1)');
```
And then run the server in `non-coroutine` mode and `coroutine` mode.
Stress testing command: `ab -k -c 1000 -t 10 http://127.0.0.1:9501/`

Non-Coroutine mode:

Coroutine mode:

### CODE REVIEW

**Comment by ezimuel** [comment]
@huangzhhui do you have more information of this new feature? Is there any reference online?
I just noticed, in the second benchmark result (with coroutine) you have **48856 Failed requests**, can you check please?

**Comment by huangzhhui** [comment]
@ezimuel The tests result maybe wrong, because my MySQL server cannot handle the huge connection numbers like this, I have to develop a Connection Pool before this, anyone could provide another tests result would be better, but coroutine still faster than non-coroutine is a fact.

**Comment by huangzhhui** [comment]
@ezimuel There is the only official documents for reference, but it's Chinese, maybe you should translate it.
https://wiki.swoole.com/wiki/page/965.html

**Comment by xtreamwayz** [comment]
> server running in coroutine mode about 1350 times faster than non-coroutine mode

That is amazing. But wouldn't it be better to benchmark against the skeleton page? This way you get of bottlenecks like you have with the MySQL connections.

**Comment by huangzhhui** [comment]
@xtreamwayz If benchmark against to a page that no I/O request, the results will almost same, because the core goals of swoole coroutine is to make I/O Blocking request become to a Non-Blocking I/O Async request, it means the workers are no need to wait the I/O response. 
Most of systems that build top on zend framework are I/O intensive system ( interacts with MySQL, Redis, HTTP request, etc. more ), same as most of Web systems, that's why I write this test cases.

**Comment by xtreamwayz** [comment]
Males sense. Thanks for explaining.

**Comment by weierophinney** [comment]
How does this impact how users should write their code? I ask, because my understanding is that these operations then become essentially asynchronous - which has impact on program execution flow.

Do users of these capabilities need to write their code any differently? If so, can you provide examples?

I ask, because I don't want to provide a toggle for it if enabling it will break "normal" applications, and we cannot provide any recommendations on what code changes they may need to make. Clearly, even from your own examples, there may be configuration changes in things such as the MySQL server necessary to accommodate the flood of connections — I cannot help but think there may also be requirements within the application itself.

Regardless, this is _fascinating_ to see happening, and if we can provide guidance to our users, could be a game changer for many PHP developers!

**Comment by huangzhhui** [comment]
@weierophinney 
There is no need to write difference code, the same with swoole usages (maybe zend-expressive-swoole, in fact zend-expressive-swoole isn't a full-featured swoole application), the code could run as expected in swoole server, then will run as expected in coroutine mode.

In my test case, because two reasons, first reason is MySQL cannot handle the huge connections, commonly the max connections is about 100, it's also a default value for MySQL; The second reason is no available connection pool for zend, connection pool is very important for an async application, because the server could handle a lots of requests now, no longer limited by PHP-FPM processes model.

Actually coroutine(Swoole Coroutine) had been changed the PHP in China.
Before Swoole Couroutine Released (Commonly also running in Swoole Server or other resident PHP server) :
Usually write coroutine application by yield + generator, like this:
```
$result = yield $db->query($sql);
```
There is a blog for reference, written by nikic(PHP core developer)
http://nikic.github.io/2012/12/22/Cooperative-multitasking-using-coroutines-in-PHP.html

After Swoole 2 Released (about 2 years ago):
Swoole offers a lots of Coroutine Client for users, like HTTP/HTTP2 Client, Mysql/PostgreSql Client, Redis Client, TCP/UDP Client, users could use these clients to write a async application now, no need to write `yield` before I/O request.
There is a official document about coroutine client, but it's Chinese, notice that the [English Documents](https://www.swoole.co.uk/coroutine) informations are outdated, swoole 4 had been solved a lots of problems as mentioned in the English Documents. 
https://wiki.swoole.com/wiki/page/749.html
In this stage, some partners and I write this [Swoft Framework](https://github.com/swoft-cloud/swoft) (It is most popular coroutine PHP framework) , it's a high performance coroutine framework base on swoole.

After Swoole 4.1 Released:
Make PDO, Mysqli, redis, soap, stream_socket_client, fsockopen,file_get_contents (Most of I/O driver) become a non-blocking async client needs just one line code `Swoole\Runtime::enableCorotuine()`, no other code anymore.
That is why I am here and submited this PR.

**Comment by huangzhhui** [comment]
@weierophinney @ezimuel @xtreamwayz 
I build a more powerful MySQL Server, and I run the test again, here are the results of my test case.

Running zend-expressivce with swoole at 1 worker (the more workers, the higher the performance, base on your server memory).

Controller code:
```php
$pdo = new \PDO($dsn, 'user', 'password');
$pdo->setAttribute(\PDO::ATTR_EMULATE_PREPARES, false);
$stmt = $pdo->prepare('SELECT sleep(1)');
$stmt->execute();
$result = $stmt->fetchAll(\PDO::FETCH_ASSOC);
```

Non-Coroutine mode:
non-coroutine
ab command: `ab -k -c 10 -n 10`
QPS: 1 qps/s

Coroutine mode (with same ab arguments):
coroutine-same-ab
ab command: `ab -k -c 10 -n 10`
QPS: 9.84 qps/s, about 10 times faster.
Because I query 1 sec in per request, and the concurrency level only 10, so this is not the max performance.

Coroutine mode ( -c 500 ) :
coroutine-more-500-5000
ab command: `ab -k -c 500 -n 5000`
QPS: 418.56 qps/s, about 418 times faster.

**Comment by weierophinney** [comment]
So, to make sure I follow correctly: enabling the coroutine support means that when you call any of the various coroutine-enabled parts of the PHP engine, Swoole will free up the scheduler while that code processes, essentially allowing other code to run at the same time (e.g., handle another request, send more data to redis, etc.). The performance benefit is due to the fact that a worker can continue to answer requests while performing work for the current request.

Is that about right?

**Comment by weierophinney** [comment]
Next question: is this configuration setting different than the `swoole.coroutine` value as reported by `php -i`? I've noticed that, by default, that setting indicates `enabled`, which means that this flag would be primarily for disabling support? Or are they unrelated?

**Comment by huangzhhui** [comment]
@weierophinney

**Comment by huangzhhui** [comment]
@weierophinney 
You are absolutely right.
And the second question, `swoole.coroutine` in `php --ri swoole` is means the swoole extension whether if enable coroutine feature, then swoole will automatically create a coroutine for each `onRequest` callback, but actually it's useless in zend-expressive-swoole or other non-coroutine applications. After Swoole 4.0, coroutine as a main feature as swoole, coroutine supported will automatically builded in swoole extension, then swoole remove the build argument `--enable-coroutine` and add a config `enable_coroutine` to control coroutine switch, in order not to waste the server resource.
This means, ONLY `swoole.coroutine` in `php --ri swoole` is `true` (default value is true), and option `enable_coroutine` of  `SwooleServer` is true (default value is true), and `\Swoole\Runtime::enableCoroutine()` function has been executed, swoole coroutine will works in zend-expressive-swoole, that's why I bonded the `enable_coroutine` option (ONLY user provide this option, not include the swoole default value) with `\Swoole\Runtime::enableCoroutine()` function to switch the coroutine feature in zend-expressive.

**Comment by kcloze** [comment]
Very good job！

**Comment by hchengvip** [comment]
That is good news for phper.

**Comment by rundaisc** [comment]
nice

**Comment by codeliner** [comment]
wow, amazing!

**Comment by hanfeicode** [comment]
good idea

**Pull request merged**
