### PR TITLE
Add `reload` command for reload all workers

### PR DESCRIPTION
**Pull request by huangzhhui**
Provide a narrative description of what you are trying to accomplish:

- [x] Are you creating a new feature?
  - [x] Why is the new feature needed? What purpose does it serve?
Provide `reload` command for reload all workers, this command ONLY run in `SWOOLE_PROCESS` mode, and ONLY can reload the code that loaded after worker start.
  - [x] How will users use the new feature?
When server running in `daemon` mode, you can run `php public/index.php reload` command to reload all workers, this action will reload the business codes that you modified.
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [x] Add only one feature per pull request; split multiple features over multiple pull requests

### CODE REVIEW

**Comment by huangzhhui** [comment]
@weierophinney Notice that this changes have not add to `CHANGELOG` yet, and any develop idea about next step ?

**Comment by weierophinney** [comment]
@huangzhhui I added the CHANGELOG entry during merge. :smiley: 

The next steps at this point:

- I'm going to rename the `RequestHandlerSwooleRunner` to either `SwooleRequestHandlerRunner` or `SwooleRunner`.
- I'm considering using symfony/console for the CLI handling. This will be a transparent change to the end-users, but make it easier for us to maintain and expand the tooling.
- I'm going to revisit the log messages and formats, and try and have them align with Apache/nginx styles. I may allow providing alternative log format strings as well.

**Comment by huangzhhui** [comment]
@weierophinney 
Swoole 4.1 is ready, there's a incredible feature that could let `PDO`, `Mysqli`, `redis`, `soap`, `stream_socket_client`, `fsockopen`,` file_get_contents` (Most of I/O driver) become a non-blocking async client needs just one line code `Swoole\Runtime::enableCorotuine()`.
Any idea about let zend framework become a coroutine framework ?

**Comment by froschdesign** [comment]
@huangzhhui 
Please don't hijack old / closed pull requests. Use the [chat](https://zendframework-slack.herokuapp.com/) or [forum](https://discourse.zendframework.com/) for this type of questions. Thanks!

**Pull request merged**
